---
gateway: 10.211.55.1
netmask: 255.255.255.0
gateway2: 10.211.55.2
netmask2: 255.255.255.0
# VMWare default ens192
# KVM default ens3
# Libvirt default enp1s0
interface: eth0
#interface2: ens224
dns: 
  - 8.8.8.8
webserver_url: 10.211.55.26
webserver_port: 81

# Drive to install RHCOS
# Libvirt - can be vda
install_drive: sda

ocp_version: 4.4
iso_checksum: dc1287165ff5b9d10e729c5541b616d466a9f0ed2e3380d59490503758a4cb24
iso_name: rhcos-{{ ocp_version }}.3-x86_64-installer.x86_64.iso
rhcos_bios: rhcos-{{ ocp_version }}.3-x86_64-metal.x86_64.raw.gz
...
